data:
  __speedrun__: __purge__
  loader_kwargs:
    batch_size: 1024
    bit_encoded_messages: false
    clip_history_days: false
    mask_current_day_encounters: true
    num_datasets_to_select: 10
    num_workers: 10
    relative_days: true
    shuffle: true
  paths:
    train: /home/mturk/dpfn/dpfn/data/train_app_users/partial/
    validate: /home/mturk/dpfn/dpfn/data/val_app_users/partial/
  validation_loader_kwargs:
    num_datasets_to_select: null
